name: PR Checks

# DISABLED: This workflow is temporarily disabled
on:
  # Using workflow_dispatch only (manual trigger) effectively disables automatic runs
  workflow_dispatch:

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 'latest'
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Lint
        run: pnpm lint
      
      - name: Build
        run: pnpm build
      
      - name: Test
        run: pnpm test 