name: Publish Package

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm test
      - run: pnpm lint
      - name: Publish beta from develop
        if: github.ref == 'refs/heads/develop'
        run: |
          pnpm version:beta
          pnpm publish:beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish production from main
        if: github.ref == 'refs/heads/main'
        run: pnpm publish:prod
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: pnpm publish:prod
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} 