name: Publish Package

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 'latest'
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
      - name: Lint
        run: pnpm lint
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Publish alpha from feature branch
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/')
        run: |
          pnpm version:alpha
          pnpm publish:alpha
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish beta from develop
        if: github.ref == 'refs/heads/develop'
        run: |
          pnpm version:beta
          pnpm publish:beta
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish production from main
        if: github.ref == 'refs/heads/main'
        run: pnpm publish:prod
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: pnpm publish:prod
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}} 